# Generated by Django 6.0.8 on 2026-09-06 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tramite', models.CharField(blank=True, max_length=20, unique=True)),
                ('tipo_servicio', models.CharField(choices=[('busqueda', 'Búsqueda de Fábrica'), ('asesoria', 'Asesoría y Validación de Compras'), ('logistica', 'Logística Internacional'), ('nacionalizacion', 'Nacionalización y Aduanas'), ('inspeccion', 'Inspección en Origen'), ('transporte_local', 'Transporte Local y Entrega'), ('representacion', 'Representación y Distribución')], max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Revisión'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleTransporteLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta_con_levante', models.CharField(max_length=100)),
                ('punto_partida', models.CharField(max_length=255)),
                ('ciudad_destino', models.CharField(max_length=255)),
                ('tipo_vehiculo', models.CharField(max_length=100)),
                ('peso_estimado', models.CharField(max_length=100)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='tramites/transporte/')),
                ('tramite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_transporte', to='core.tramite')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRepresentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=50)),
                ('canales_distribucion', models.CharField(max_length=100)),
                ('nombre_fabrica_china', models.CharField(max_length=255)),
                ('alcance_representacion', models.CharField(max_length=100)),
                ('proyeccion_anual', models.CharField(blank=True, max_length=100, null=True)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='tramites/representacion/')),
                ('tramite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_representacion', to='core.tramite')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleNacionalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_comercial', models.TextField()),
                ('uso_aplicacion', models.CharField(max_length=255)),
                ('valor_fob', models.DecimalField(decimal_places=2, max_digits=10)),
                ('certificado_origen', models.CharField(max_length=50)),
                ('entidad_control', models.CharField(max_length=100)),
                ('tipo_regimen', models.CharField(max_length=100)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='tramites/nacionalizacion/')),
                ('tramite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_nacionalizacion', to='core.tramite')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleLogistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_carga', models.CharField(max_length=100)),
                ('incoterm', models.CharField(max_length=50)),
                ('puerto_origen', models.CharField(max_length=100)),
                ('puerto_destino', models.CharField(max_length=100)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='tramites/logistica/')),
                ('tramite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_logistica', to='core.tramite')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=255)),
                ('ciudad_china', models.CharField(max_length=100)),
                ('cantidad_unidades', models.IntegerField()),
                ('tipo_control', models.CharField(max_length=100)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='tramites/inspeccion/')),
                ('tramite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_inspeccion', to='core.tramite')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleBusquedaFabrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=255)),
                ('marca_referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_contacto', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=50)),
                ('ha_importado_antes', models.CharField(max_length=50)),
                ('link_producto', models.URLField(blank=True, null=True)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='tramites/busqueda/')),
                ('cantidad_estimada', models.CharField(blank=True, max_length=100, null=True)),
                ('especificaciones', models.TextField(blank=True, null=True)),
                ('tramite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_busqueda', to='core.tramite')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleAsesoriaCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=50)),
                ('donde_encontro_proveedor', models.CharField(max_length=100)),
                ('estado_negociacion', models.CharField(max_length=100)),
                ('monto_aproximado', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_asesoria_urgencia', models.CharField(max_length=100)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='tramites/asesoria/')),
                ('tramite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_asesoria', to='core.tramite')),
            ],
        ),
    ]
