# Generated by Django 6.0.8 on 2026-09-08 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AliadoEstrategico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=150, verbose_name='Nombre de la Agencia/Aliado')),
                ('contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Persona de Contacto')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico de Cotizaciones')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono')),
                ('tipo_servicio', models.CharField(choices=[('busqueda', 'Búsqueda de Fábrica'), ('asesoria', 'Asesoría y Validación de Compras'), ('logistica', 'Logística Internacional'), ('nacionalizacion', 'Nacionalización y Aduanas'), ('inspeccion', 'Inspección en Origen'), ('transporte_local', 'Transporte Local'), ('representacion', 'Representación y Distribución')], max_length=50, verbose_name='Especialidad')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
            ],
        ),
        migrations.AddField(
            model_name='tramite',
            name='enviado_a_aliado',
            field=models.BooleanField(default=False, verbose_name='¿Enviado a cotizar?'),
        ),
        migrations.AddField(
            model_name='tramite',
            name='fecha_envio_aliado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío al Aliado'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tramites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tramite',
            name='aliado_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramites_asignados', to='core.aliadoestrategico', verbose_name='Aliado Estratégico'),
        ),
    ]
