# Generated by Django 6.0.8 on 2026-09-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aliadoestrategico_tramite_enviado_a_aliado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliadoestrategico',
            name='tipo_servicio',
            field=models.JSONField(blank=True, default=list, verbose_name='Especialidades / Servicios'),
        ),
    ]
