# Generated by Django 6.1.1 on 2026-09-25 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_historialdocumentotrámite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aliadoestrategico',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='aliadoestrategico',
            name='email',
        ),
        migrations.RemoveField(
            model_name='aliadoestrategico',
            name='nombre_empresa',
        ),
        migrations.RemoveField(
            model_name='aliadoestrategico',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='aliadoestrategico',
            name='tipo_servicio',
        ),
        migrations.AddField(
            model_name='aliadoestrategico',
            name='especialidad_asesoria',
            field=models.BooleanField(default=False, verbose_name='Asesoría y Validación de Compras'),
        ),
        migrations.AddField(
            model_name='aliadoestrategico',
            name='especialidad_busqueda',
            field=models.BooleanField(default=False, verbose_name='Búsqueda de Fábrica'),
        ),
        migrations.AddField(
            model_name='aliadoestrategico',
            name='especialidad_inspeccion',
            field=models.BooleanField(default=False, verbose_name='Inspección en Origen'),
        ),
        migrations.AddField(
            model_name='aliadoestrategico',
            name='especialidad_logistica',
            field=models.BooleanField(default=False, verbose_name='Logística Internacional'),
        ),
        migrations.AddField(
            model_name='aliadoestrategico',
            name='especialidad_nacionalizacion',
            field=models.BooleanField(default=False, verbose_name='Nacionalización y Aduanas'),
        ),
        migrations.AddField(
            model_name='aliadoestrategico',
            name='especialidad_representacion',
            field=models.BooleanField(default=False, verbose_name='Representación y Distribución'),
        ),
        migrations.AddField(
            model_name='aliadoestrategico',
            name='especialidad_transporte_local',
            field=models.BooleanField(default=False, verbose_name='Transporte Local y Entrega'),
        ),
        migrations.AddField(
            model_name='aliadoestrategico',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='aliadoestrategico',
            name='nombre_agencia',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de la Agencia / Aliado'),
        ),
        migrations.CreateModel(
            name='ContactoAliado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=100, verbose_name='Persona de Contacto')),
                ('correo_cotizaciones', models.EmailField(max_length=254, verbose_name='Correo Electrónico de Cotizaciones')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono')),
                ('es_principal', models.BooleanField(default=False, verbose_name='¿Es contacto principal?')),
                ('aliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='core.aliadoestrategico', verbose_name='Empresa Aliada')),
            ],
        ),
    ]
